[profile.default]
solc = '0.8.23'
evm_version = 'paris' # Required for L2s (Optimism, Arbitrum, etc.)
# grant access to the deployment addresses for the registry test:
fs_permissions = [{ access = "read", path = "./lib/juice-address-registry/broadcast/Deploy.s.sol"}]
gas_reports_ignore = [
    "JBTokens",
    "JBSplits",
    "JBTerminalStore",
    "JBProjects",
    "JBRulesets",
    "JBMultiTerminal",
    "JBDirectory",
    "JBController",
    "AccessJBLib",
    "JBIpfsDecoder",
    "ForTest_JB721TiersHook",
    "ForTest_JB721TiersHookStore",
    "JB721TiersHookStore",
]
optimizer_runs = 200
block_timestamp = 1674745056

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true

